[package]
name = "RSCube"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0"
byteorder = "1"

[[bin]]
name = "RSCube"
path = "main.rs"
